### PR TITLE
Add David Pacheco's favorite number

### PR DESCRIPTION
**Pull request by davidmv74**
Working through tasks :)

### CODE REVIEW

**Comment by sfelshin** [comment]
@davidmv74, I see you requested review from me.  You should also assign the issue to me so that I know I'm the party who is currently responsible for working on it.  Otherwise, I might think you requested my eventual review but aren't actually ready for review yet.  A PR should always be assigned to _someone_ (except in the rare and unfortunate circumstance where someone departs the group before merging their PR and without assigning a replacement person, leaving the PR temporarily(?) orphaned).

**Comment by davidmv74** [comment]
Ahh I missed that, thanks for the note! Adding you now.

**Comment by sfelshin** [comment]
@davidmv74, you assigned the PR to me, but then you didn't wait for my review!  When you assigned me the PR, GitHub sent me a notification email.  You should have waited for me to see the email and review the PR.  Please make a new PR (you can change your mind about your favorite number) and let's go through the full process, for practice.

**Comment by davidmv74** [comment]
Ahh, sorry about that. I saw merging as an option so I assumed that meant a
review had been done. Does it allow merging without review? That seems
dangerous.
Will create a new one soon!
-David

**Pull request merged**
