### PR TITLE
Add Orion's favorite number

### PR DESCRIPTION
**Pull request by OrionLi545**
Finishing the welcome demo by PR-ing my fav number into the CSV file

### CODE REVIEW

**Review by sfelshin — APPROVED** [review]
LGTM!

**Comment by sfelshin** [comment]
@OrionLi545, please delete the branch after you merge the PR. Although it's possible to continue working in a branch after merging a PR for that branch, there are a variety of reasons why it's Considered Harmful. In the Infolab, we choose to delete the branch after merging, even if it's to fix a bug in the merged PR. (If you branch a subbranch off of a parent branch, this applies to the subbranch when you merge its PR, but it doesn't apply to the parent branch until you merge the parent branch's PR. And of course some branches get abandoned without ever getting PRs created or merged.)

**Comment by OrionLi545** [comment]
OK, I got it. Will delete the branch right now.

**Comment by sfelshin** [comment]
@OrionLi545, I see I left out half a sentence above. 🤦 I meant "In the Infolab, we choose to delete the branch after merging, _and to always make a new branch_ even if it's to fix a bug in the merged PR.

**Pull request merged**
