### PR TITLE
Add Chris's favorite number

### PR DESCRIPTION
**Pull request by czlwang**
Adding my favorite number for practice.

### CODE REVIEW

**Comment by sfelshin** [comment]
@czwmit, you requested my review but you didn't assign the issue to me, so I assume the issue isn't my responsibility at this time. Although if you're still working on it and it's not ready for review yet, you should have assigned it to yourself. 😄  Probably you meant to assign it to me, but I'll wait for that before I review the PR.

You may find it helpful to review [Github workflow](https://projects.csail.mit.edu/cgi-bin/wiki/view/Infolab/GithubWorkflow).

**Comment by czlwang** [comment]
Ah! I understand the difference now - thanks. I've assigned this issue to myself and you now.

**Comment by sfelshin** [comment]
@czwmit, now the issue is assigned to _both_ you _and_ me.  Since you're an assignee, I assume you're actively working on the issue.  Should I hold off on my review?  Hmm...

It's very annoying of me to make you jump through all these hoops when you obviously mean the issue is ready for my review now.  But I promise you, you will be glad later to be accustomed to using both the Review and Assignee sections in order to assign general responsibility for reviewing vs. immediate responsibility for working on the issue.

**Comment by czlwang** [comment]
No problem at all. Thank you for clarifying! So, I see that "assigned" means "actively working on".

**Review by sfelshin — APPROVED** [review]
LGTM!

**Pull request merged**
