### PR TITLE
Add Allen's favorite number

### PR DESCRIPTION
**Pull request by alhuan**
Added Allen's favorite number

### CODE REVIEW

**Comment by sfelshin** [comment]
Hi, @allen-huang1.  I see you requested my review but you haven't assigned the PR to me. Therefore, I assume the PR isn't ready for review yet.  When it's ready for review, please assign it to me.

**Comment by alhuan** [comment]
Sorry, I can't figure out how to assign the PR. Where do I go for that?

**Comment by sfelshin** [comment]
Under the list of Reviewers is a list of Assignees.  Think of Reviewers as "people who should review this PR at the appropriate time (to be determined elsewhere)" and Assignees as "people who are responsible for working on this PR _right now_".  I see that while I was typing this, you figured it out!

**Comment by alhuan** [comment]
Yes, thank you for the clarification!

**Review by sfelshin — CHANGES_REQUESTED** [review]
Every unix file should end in a newline.  Also, it's very odd that Github claims that you changed every line of the file.  Is there a CRLF issue?

**Comment by alhuan** [comment]
I'm not sure exactly what went wrong, I just used the vi file editor in command line to add myself in.

**Review by sfelshin — APPROVED** [review]
LGTM

**Comment by sfelshin** [comment]
Hint: when you reassigned the PR to me, you should have unassigned yourself. That way, when I reassigned the PR to you, Github would have sent you a notification. Since you were already assigned, you don't get a message.  (Except that you'll get a message about this comment.)

**Comment by sfelshin** [comment]
> I'm not sure exactly what went wrong, I just used the vi file editor in command line to add myself in.

Hm, maybe vi defaults to different CRLFing? I don't know—I always use Emacs.

https://infolab-csail.slack.com/archives/C0HLCSV8U/p1580330944079900 😄

**Comment by sfelshin** [comment]
@allen-huang1 , this PR is still sitting around open. I approved it and reassigned it to you. Unless there's more to do, you should merge it and delete the branch.

**Comment by sfelshin** [comment]
@allen-huang1: And delete the branch, please.

**Pull request merged**
