### PR TITLE
Add Alan's favorite number

### PR DESCRIPTION
**Pull request by alany1**

### CODE REVIEW

**Comment by hanryhu** [comment]
for reviewers: even though [Travis is down](https://github.com/infolab-csail/infolab-core/issues/255), it should still run for this repo since it's "open source".

**Comment by sfelshin** [comment]
@alany1, I see you requested review from me but didn't assign the PR to me.  I assume that means the PR isn't ready for me to review yet.

(Actually, I assume you overlooked assigning it to me.  Our Welcome Demo is about learning best practices for Git and GitHub.  Use the Assignees section to assign _current_ responsibility for issues and PRs. GitHub will send a message to each new assignee, making it a convenient way to pass responsibility back and forth.)

**Comment by alany1** [comment]
> @alany1, I see you requested review from me but didn't assign the PR to me. I assume that means the PR isn't ready for me to review yet.
> 
> (Actually, I assume you overlooked assigning it to me. Our Welcome Demo is about learning best practices for Git and GitHub. Use the Assignees section to assign _current_ responsibility for issues and PRs. GitHub will send a message to each new assignee, making it a convenient way to pass responsibility back and forth.)

Got it, thanks for letting me know!

**Review by sfelshin — APPROVED** [review]
LGTM!

**Pull request merged**
