### PR TITLE
Add Hannah's favorite number

### PR DESCRIPTION
**Pull request by redhann**

### CODE REVIEW

**Review by sfelshin — APPROVED** [review]
LGTM!

**Comment by sfelshin** [comment]
Hi, @redhann, why'd you assign this to me?  It's a merged PR and you're both the originator and the person who merged it, so it seems like it should have been left assigned to you.  Do you want me to do something more with this PR?

**Comment by redhann** [comment]
Oops! Sorry @sfelshin, I was showing Rachel what the welcome demo looked like and accidentally assigned you to this PR instead of my open one.

**Comment by sfelshin** [comment]
No worries! Thanks for showing Rachel stuff.

**Pull request merged**
